{
 "title": "Weather Forecast",
 "time": { "from": "now-1d", "to": "now+7d" },
 "templating": {
  "list": [
   {
    "name": "date",
    "label": "Date",
    "query": {}
   },
   {
    "name": "continent",
    "label": "Continent",
    "query": {}
   },
   {
    "name": "country",
    "label": "Country",
    "query": {}
   },
   {
    "name": "city",
    "label": "City",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": " <h1 style=\"text-align: center; width: 100%; color: white;\">\r\n  城市一周天氣預測\r\n</h1>"
   }
  },
  {
   "title": "氣溫(攝氏)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "project": "project-12c56ec2-0f93-4ccd-a36",
     "rawSql": "SELECT\r\n  CAST(DATETIME(f.target_time) AS TIMESTAMP) AS time,\r\n  f.pred_temp AS temperature,\r\n  d.city_name AS city\r\nFROM `project-12c56ec2-0f93-4ccd-a36.weather_data.fact_forecasts` AS f\r\nJOIN `project-12c56ec2-0f93-4ccd-a36.weather_data.dim_cities` AS d \r\n  ON f.city_id = d.city_id\r\nWHERE\r\n  -- 這裡串連你設定好的 4 個變數\r\n  d.continent IN (${continent:sqlstring})\r\n  AND d.country IN (${country:sqlstring})\r\n  AND d.city_name IN (${city:sqlstring})\r\n  AND f.forecast_date = CAST('${date}' AS DATE)\r\nORDER BY f.target_time ASC"
    }
   ]
  },
  {
   "title": "體感溫度(攝氏)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 2 },
   "targets": [
    {
     "project": "project-12c56ec2-0f93-4ccd-a36",
     "rawSql": "SELECT\r\n  CAST(DATETIME(f.target_time) AS TIMESTAMP) AS time,\r\n  f.pred_apparent_temp AS apparent_temperature,\r\n  d.city_name AS city\r\nFROM `project-12c56ec2-0f93-4ccd-a36.weather_data.fact_forecasts` AS f\r\nJOIN `project-12c56ec2-0f93-4ccd-a36.weather_data.dim_cities` AS d \r\n  ON f.city_id = d.city_id\r\nWHERE\r\n  -- 這裡串連你設定好的 4 個變數\r\n  d.continent IN (${continent:sqlstring})\r\n  AND d.country IN (${country:sqlstring})\r\n  AND d.city_name IN (${city:sqlstring})\r\n  AND f.forecast_date = CAST('${date}' AS DATE)\r\nORDER BY f.target_time ASC"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "description": "數值 > 6 建議加強防曬，> 11 應避免在室外停留。",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "project": "project-12c56ec2-0f93-4ccd-a36",
     "rawSql": "SELECT\r\n  CAST(DATETIME(f.target_time) AS TIMESTAMP) AS time,\r\n  d.city_name AS city,\r\n  f.pred_uv AS uv\r\nFROM `project-12c56ec2-0f93-4ccd-a36.weather_data.fact_forecasts` AS f\r\nJOIN `project-12c56ec2-0f93-4ccd-a36.weather_data.dim_cities` AS d \r\n  ON f.city_id = d.city_id\r\nWHERE\r\n  -- 這裡串連你設定好的 4 個變數\r\n  d.continent IN (${continent:sqlstring})\r\n  AND d.country IN (${country:sqlstring})\r\n  AND d.city_name IN (${city:sqlstring})\r\n  AND f.forecast_date = CAST('${date}' AS DATE)\r\nORDER BY f.target_time ASC"
    }
   ]
  },
  {
   "title": "雲量",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "project": "project-12c56ec2-0f93-4ccd-a36",
     "rawSql": "SELECT\r\n  CAST(DATETIME(f.target_time) AS TIMESTAMP) AS time,\r\n  f.pred_cloud_cover AS cloud_cover,\r\n  d.city_name AS city\r\nFROM `project-12c56ec2-0f93-4ccd-a36.weather_data.fact_forecasts` AS f\r\nJOIN `project-12c56ec2-0f93-4ccd-a36.weather_data.dim_cities` AS d \r\n  ON f.city_id = d.city_id\r\nWHERE\r\n  -- 這裡串連你設定好的 4 個變數\r\n  d.continent IN (${continent:sqlstring})\r\n  AND d.country IN (${country:sqlstring})\r\n  AND d.city_name IN (${city:sqlstring})\r\n  AND f.forecast_date = CAST('${date}' AS DATE)\r\nORDER BY f.target_time ASC"
    }
   ]
  },
  {
   "title": "濕度",
   "type": "timeseries",
   "description": "濕度 > 70% 太潮濕，40% - 60% 為舒適範圍。",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "project": "project-12c56ec2-0f93-4ccd-a36",
     "rawSql": "SELECT\r\n  CAST(DATETIME(f.target_time) AS TIMESTAMP) AS time,\r\n  f.pred_humidity AS humidity,\r\n  d.city_name AS city\r\nFROM `project-12c56ec2-0f93-4ccd-a36.weather_data.fact_forecasts` AS f\r\nJOIN `project-12c56ec2-0f93-4ccd-a36.weather_data.dim_cities` AS d \r\n  ON f.city_id = d.city_id\r\nWHERE\r\n  -- 這裡串連你設定好的 4 個變數\r\n  d.continent IN (${continent:sqlstring})\r\n  AND d.country IN (${country:sqlstring})\r\n  AND d.city_name IN (${city:sqlstring})\r\n  AND f.forecast_date = CAST('${date}' AS DATE)\r\nORDER BY f.target_time ASC"
    }
   ]
  },
  {
   "title": "雨量",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 28 },
   "targets": [
    {
     "project": "project-12c56ec2-0f93-4ccd-a36",
     "rawSql": "SELECT\r\n  CAST(DATETIME(f.target_time) AS TIMESTAMP) AS time,\r\n  f.pred_rain AS rain,\r\n  d.city_name AS city\r\nFROM `project-12c56ec2-0f93-4ccd-a36.weather_data.fact_forecasts` AS f\r\nJOIN `project-12c56ec2-0f93-4ccd-a36.weather_data.dim_cities` AS d \r\n  ON f.city_id = d.city_id\r\nWHERE\r\n  -- 這裡串連你設定好的 4 個變數\r\n  d.continent IN (${continent:sqlstring})\r\n  AND d.country IN (${country:sqlstring})\r\n  AND d.city_name IN (${city:sqlstring})\r\n  AND f.forecast_date = CAST('${date}' AS DATE)\r\nORDER BY f.target_time ASC"
    }
   ]
  },
  {
   "title": "空氣品質",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 41 },
   "targets": [
    {
     "project": "project-12c56ec2-0f93-4ccd-a36",
     "rawSql": "SELECT\r\n  CAST(DATETIME(f.target_time) AS TIMESTAMP) AS time,\r\n  f.pred_aqi AS aqi,\r\n  d.city_name AS city\r\nFROM `project-12c56ec2-0f93-4ccd-a36.weather_data.fact_forecasts` AS f\r\nJOIN `project-12c56ec2-0f93-4ccd-a36.weather_data.dim_cities` AS d \r\n  ON f.city_id = d.city_id\r\nWHERE\r\n  -- 這裡串連你設定好的 4 個變數\r\n  d.continent IN (${continent:sqlstring})\r\n  AND d.country IN (${country:sqlstring})\r\n  AND d.city_name IN (${city:sqlstring})\r\n  AND f.forecast_date = CAST('${date}' AS DATE)\r\nORDER BY f.target_time ASC"
    }
   ]
  }
 ]
}